### ISSUE TITLE
bug: getNextObject getPrevObject should work if the key provided is unknown

### ISSUE THREAD

**Issue by joticajulian** [roaminroe/koinos-mock-vm#4]
How to reproduce?
```
key = new Uint8Array(1); // this is an unknown key
result = getNextObject(space, key);
```
In the current implementation `result` is always `null` because it can not find the `key`. However, the existence of this key should be optional. It should use it as reference to get the lower bound and search from that point https://github.com/koinos/koinos-chain/blob/3a2974927b627f6f3fcc5cadabfa5578ea68808b/libraries/state_db/state_db.cpp#L452

**Comment by roaminroe** [comment]
fixed in latest realease, thanks for finding this bug @joticajulian!
